spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: usuario_demo
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#  Secure Password requirements ej:

#  Password must contain at least one digit [0-9].
#  Password must contain at least one lowercase Latin character [a-z].
#  Password must contain at least one uppercase Latin character [A-Z].
#  Password must contain at least one special character like ! @ # & ( ).
#  Password must contain a length of at least 8 characters and a maximum of 20 characters.

application:
  security:
    password:
      pattern: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()?[{}]:;',?/*~$^+=<>]).{8,20}$
